/// @description  icons_init()
/// @function  icons_init
function icons_init() {

	enum icons {
	    NEW,
	    OPEN,
	    SAVE,
	    SAVE_AS,
	    PLAY,
	    PAUSE,
	    STOP,
	    BACK,
	    FORWARD,
	    RECORD,
	    INS_1,
	    INS_2,
	    INS_3,
	    INS_4,
	    INS_5,
	    INS_6,
	    INS_7,
	    INS_8,
	    INS_9,
	    INS_10,
	    INS_11,
	    INS_12,
	    INS_13,
	    INS_14,
	    INS_15,
	    INS_16,
	    CUSTOM_INS_1,
	    CUSTOM_INS_2,
	    CUSTOM_INS_3,
	    CUSTOM_INS_4,
	    CUSTOM_INS_5,
	    CUSTOM_INS_6,
	    CUSTOM_INS_7,
	    CUSTOM_INS_8,
	    CUSTOM_INS_9,
	    CUSTOM_INS_10,
	    CUSTOM_INS_11,
	    CUSTOM_INS_12,
	    CUSTOM_INS_13,
	    CUSTOM_INS_14,
	    CUSTOM_INS_15,
	    CUSTOM_INS_16,
	    CUSTOM_INS_17,
	    CUSTOM_INS_18,
	    UNDO_INACTIVE,
	    UNDO,
	    REDO_INACTIVE,
	    REDO,
	    COPY_INACTIVE,
	    COPY,
	    CUT_INACTIVE,
	    CUT,
	    PASTE_INACTIVE,
	    PASTE,
	    DELETE_INACTIVE,
	    DELETE,
	    INFORMATION,
	    PROPERTIES,
	    INSTRUMENTS,
	    MIDI_INPUT,
	    HELP,
	    INTERNET,
	    CHECK,
	    SUB_MENU,
		CHECK_INACTIVE,
		LOOP_INACTIVE,
		LOOP,
		METRONOME_INACTIVE,
		METRONOME_1,
		METRONOME_2,
		EDITMODE_KEY,
		EDITMODE_VEL,
		EDITMODE_PAN,
		EDITMODE_PIT,
		INSBOX_EXPAND,
		INSBOX_COLLAPSE
	}



}
